sudo: required

dist: xenial

os:
  - linux

language: python

env:
  global:
    # Doctr deploy key for pyvista/pyvista-docs
    - secure: "NfcxZ7xmwR7F1Hrx87nMLtX+LwoessJPcDo5e/6HOiDqpuuomvAJZOrghUMfZah6cbpTRRbj7yXNrof1abXD4KLKrPVBsx2KNFqg8vsYNNpfc4fDpZFJUIDoa5rNzs9QuJPSE5/wzzxiyRT8hnnARD6FUjTvbhVJG2XTLWX7xTsily18JhG6ZIHY/Kv+KgR5wpBd9tdjbJpNIuoAQ200M6v+lFXQVylKxOS2fzrZVk95SghPJtQtwBq+IAM07jkCq+MohKOfy/pVnvm0YGQe6xIrMFuqSTzDV3fO//0IV+Vxl4nnsAC9irCMSBCA18GphyU2EKG8wCk21TkCZgvmJqjoLESe9vTMnlRzIg9x0pabhb19m+ToqVZWXASFTSYAYgLbhrqlCUKgJhcouuQWO5D0wFFov4Ur1W4Y8oMezqBkDqiJjf4gm7Qodg7wwsihkluAaxddUUkz3d9wZWi5Qqv/KQ61wah5D7De3OGON/FCo/d8BaomKF1fD978/yyy832Il0GpG7QOTWTFpxGM0UQ1A/5/QQmjJu0EN24dLAKf0RrFIXcflibrudQy/XxWOS/K+uqil6mENLJc5QukMhZqCp77Pb0zQM7nAWWgoGU/Gq+uQheeRnxiplyZp32LBGPWTLrbeU8HRmN9kMxKsT/GZhQw/UVRY0W2HeQZCq8="

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh

install:
  - pip install -r requirements.txt
  - pip install -r requirements_docs.txt
  - pip install -U doctr
  - pip install cookiecutter
  - pip install -e .
  - which python
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - pip list
  - python -c "import pyvista; print(pyvista.Report())"

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_JOB_NUMBER
  - echo $TRAVIS_REPO_SLUG

matrix:
  include:
    # Test the core API on Python 3.5, 3.6, and 3.7
    - name: Core API 3.5
      python: 3.5
      # Run the test suite and generate coverage report
      script: pytest -v --cov pyvista
    - name: Core API 3.6
      python: 3.6
      # Run the test suite and generate coverage report
      script: pytest -v --cov pyvista
    - name: Core API 3.7
      python: 3.7
      env:
        - REPORT_COVERAGE: true
        # Deploy to PyPI when core testing passes on 3.7 on tags
        - PYVISTA_DEPLOY: true
      # Run the test suite and generate coverage report
      script: pytest -v --cov pyvista

    # Test the package docstrings on Python 3.5, 3.6, and 3.7
    - name: Package Docstrings 3.5
      python: 3.5
      # Run all code examples in the docstrings
      script: pytest -v --doctest-modules pyvista
    - name: Package Docstrings 3.6
      python: 3.6
      # Run all code examples in the docstrings
      script: pytest -v --cov --doctest-modules pyvista
    - name: Package Docstrings 3.7
      python: 3.7
      env:
        - REPORT_COVERAGE: true
      # Run all code examples in the docstrings
      script: pytest -v --cov --doctest-modules pyvista
    # Build/test/deploy documentation on 3.7 only
    - name: Documentation Testing 3.7
      python: 3.7
      script: |
        pip install codespell pydocstyle;
        make doctest;
    - name: Documentation Build/Deploy 3.7
      python: 3.7
      env:
        - REPORT_COVERAGE: false
        - DEPLOY_DOCS: true
      # Run `make html` before `make doctest` to avoid segfault.
      # Then rerun `make html` to use updated figures from `make doctest`
      script: |
        cd ./docs/;
        export PYVISTA_OFFSCREEN=True;
        set -e;
        make html;
        make doctest;
        make html;
        cd ..;


after_success:
  - if [[($TRAVIS_PYTHON_VERSION == 3.7) && ($REPORT_COVERAGE == 'true')]]; then
      echo "Uploading coverage to Codecov";
      codecov;
    fi

cache:
  directories:
  - "$HOME/.cache/pip"

deploy:
  - provider: script
    script: sh ./docs/deploy_docs_from_travis.sh
    skip_cleanup: true
    on:
      condition: ($TRAVIS_PYTHON_VERSION == 3.7) && ($TRAVIS_REPO_SLUG == 'pyvista/pyvista') && ($TRAVIS_BRANCH == 'master') && ($DOCS_TRIGGER == 'BANE_RULES' && ($DEPLOY_DOCS == 'true'))
  - provider: pypi
    user: akaszynski
    distributions: sdist
    on:
      condition: ($TRAVIS_PYTHON_VERSION == 3.7) && ($PYVISTA_DEPLOY == 'true')
      tags: true
    password: $PYPI_PASSWORD

notifications:
  email: false
