default_context:
    repo_name: "vista-examples"
    github_account: "pyvista"
    description: "Quick examples demonstrating what ``vista`` can do! Simply launch this Binder project and test drive ``vista``"
    author_name: "vista Developers"
    year: "2019"
